// ERP DATA ACCESS LAYER
import{supabase}from'./supabase';import type{Company,Ledger,StockItem,Voucher,SyncState,SyncRun,ManualStockBaseline,ManualBankBalance,CompanySettings,PaginatedResponse,ApiResult}from'./types';
function he<T>(e:unknown):ApiResult<T>{const m=e instanceof Error?e.message:String(e);return{data:null,error:m};}function ok<T>(d:T):ApiResult<T>{return{data:d,error:null};}
export async function getCompanies():Promise<ApiResult<Company[]>>{const{data,error}=await supabase.from('companies').select('*').order('name');if(error)return he(error);return ok(data||[]);}
export async function getCompany(id:string):Promise<ApiResult<Company>>{const{data,error}=await supabase.from('companies').select('*').eq('id',id).single();if(error)return he(error);return ok(data);}
export async function getLedgers(cid:string,o?:{classification?:string;search?:string;sortField?:string;sortOrder?:'asc'|'desc'}):Promise<ApiResult<Ledger[]>>{let q=supabase.from('ledgers').select('*').eq('company_id',cid);if(o?.classification)q=q.eq('classification',o.classification);if(o?.search)q=q.ilike('name',`%${o.search}%`);const sf=o?.sortField||'closing_balance';const so=o?.sortOrder||'desc';if(sf==='closing_balance')q=q.order('closing_balance',{ascending:so==='asc'});else q=q.order(sf,{ascending:so==='asc'});const{data,error}=await q.limit(10000);if(error)return he(error);return ok(data||[]);}
export async function getLedgerById(id:string):Promise<ApiResult<Ledger>>{const{data,error}=await supabase.from('ledgers').select('*').eq('id',id).single();if(error)return he(error);return ok(data);}
export async function getCustomers(cid:string,s?:string):Promise<ApiResult<Ledger[]>>{return getLedgers(cid,{classification:'customer',search:s,sortField:'closing_balance',sortOrder:'desc'});}
export async function getSuppliers(cid:string,s?:string):Promise<ApiResult<Ledger[]>>{return getLedgers(cid,{classification:'supplier',search:s,sortField:'closing_balance',sortOrder:'desc'});}
export async function getBanks(cid:string):Promise<ApiResult<Ledger[]>>{return getLedgers(cid,{classification:'bank',sortField:'name',sortOrder:'asc'});}
export async function getStockItems(cid:string,s?:string):Promise<ApiResult<StockItem[]>>{let q=supabase.from('stock_items').select('*').eq('company_id',cid).order('name');if(s)q=q.ilike('name',`%${s}%`);const{data,error}=await q.limit(10000);if(error)return he(error);return ok(data||[]);}
export async function getStockItemById(id:string):Promise<ApiResult<StockItem>>{const{data,error}=await supabase.from('stock_items').select('*').eq('id',id).single();if(error)return he(error);return ok(data);}
export interface VoucherFilter{companyId:string;voucherType?:string;fromDate?:string;toDate?:string;search?:string;partyLedgerId?:string;page?:number;pageSize?:number;}
export async function getVouchers(f:VoucherFilter):Promise<ApiResult<PaginatedResponse<Voucher>>>{let q=supabase.from('vouchers').select('*',{count:'exact'}).eq('company_id',f.companyId);if(f.voucherType)q=q.eq('voucher_type',f.voucherType);if(f.fromDate)q=q.gte('voucher_date',f.fromDate);if(f.toDate)q=q.lte('voucher_date',f.toDate);if(f.search)q=q.or(`voucher_number.ilike.%${f.search}%,party_name.ilike.%${f.search}%`);if(f.partyLedgerId)q=q.eq('party_ledger_id',f.partyLedgerId);const pg=f.page||1;const ps=f.pageSize||50;const from=(pg-1)*ps;const to=from+ps-1;const{data,error,count}=await q.order('voucher_date',{ascending:false}).order('voucher_number',{ascending:false}).range(from,to);if(error)return he(error);return ok({data:data||[],count:count||0,error:null});}
export async function getVoucherById(id:string,cid:string):Promise<ApiResult<Voucher>>{const{data:v,error}=await supabase.from('vouchers').select('*').eq('id',id).eq('company_id',cid).single();if(error)return he(error);if(!v)return{data:null,error:'Voucher not found'};const[ir,lr,tr]=await Promise.all([supabase.from('voucher_items').select('*').eq('voucher_id',id),supabase.from('voucher_ledger_entries').select('*').eq('voucher_id',id),supabase.from('voucher_taxes').select('*').eq('voucher_id',id)]);return ok({...v,items:ir.data||[],ledger_entries:lr.data||[],taxes:tr.data||[]});}
export async function getVouchersByLedger(cid:string,lid:string,fd?:string,td?:string,pg?:number,ps?:number):Promise<ApiResult<PaginatedResponse<import('./types').VoucherLedgerEntry&{vouchers:Voucher}>>>{let q=supabase.from('voucher_ledger_entries').select('*,vouchers!inner(*)',{count:'exact'}).eq('company_id',cid).eq('ledger_id',lid);if(fd)q=q.gte('vouchers.voucher_date',fd);if(td)q=q.lte('vouchers.voucher_date',td);const p=pg||1;const s=ps||50;const{data,error,count}=await q.order('voucher_id',{ascending:false}).range((p-1)*s,p*s-1);if(error)return he(error);return ok({data:data||[],count:count||0,error:null});}
export async function getTopDebtors(cid:string,limit=5):Promise<ApiResult<Ledger[]>>{const{data,error}=await supabase.from('ledgers').select('*').eq('company_id',cid).eq('classification','customer').order('closing_balance',{ascending:false}).limit(limit);if(error)return he(error);return ok(data||[]);}
export async function getTopCreditors(cid:string,limit=5):Promise<ApiResult<Ledger[]>>{const{data,error}=await supabase.from('ledgers').select('*').eq('company_id',cid).eq('classification','supplier').order('closing_balance',{ascending:false}).limit(limit);if(error)return he(error);return ok(data||[]);}
export async function getRecentVouchers(cid:string,limit=20):Promise<ApiResult<Voucher[]>>{const{data,error}=await supabase.from('vouchers').select('*').eq('company_id',cid).order('created_at',{ascending:false}).limit(limit);if(error)return he(error);return ok(data||[]);}
export async function getSyncState(cid:string):Promise<ApiResult<SyncState>>{const{data,error}=await supabase.from('sync_state').select('*').eq('company_id',cid).maybeSingle();if(error)return he(error);return ok(data||{id:'',company_id:cid,initial_sync_completed:false,initial_sync_started_at:null,initial_sync_completed_at:null,last_successful_sync_at:null,last_successful_voucher_date:null,last_successful_voucher_boundary:null,current_sync_started_at:null,current_sync_status:'idle',current_sync_error:null,current_sync_progress:null,created_at:'',updated_at:''});}
export async function getSyncRuns(cid:string,limit=20):Promise<ApiResult<SyncRun[]>>{const{data,error}=await supabase.from('sync_runs').select('*').eq('company_id',cid).order('started_at',{ascending:false}).limit(limit);if(error)return he(error);return ok(data||[]);}
export async function getManualStockBaseline(cid:string,sid:string):Promise<ApiResult<ManualStockBaseline>>{const{data,error}=await supabase.from('manual_stock_baselines').select('*').eq('company_id',cid).eq('stock_item_id',sid).maybeSingle();if(error)return he(error);return ok(data);}
export async function getManualBankBalance(cid:string,bid:string):Promise<ApiResult<ManualBankBalance>>{const{data,error}=await supabase.from('manual_bank_balances').select('*').eq('company_id',cid).eq('bank_ledger_id',bid).maybeSingle();if(error)return he(error);return ok(data);}
export async function getCompanySettings(cid:string):Promise<ApiResult<CompanySettings>>{const{data,error}=await supabase.from('company_settings').select('*').eq('company_id',cid).maybeSingle();if(error)return he(error);return ok(data);}
export async function getStockMovements(cid:string,sid:string,o?:{page?:number;pageSize?:number}):Promise<ApiResult<PaginatedResponse<import('./types').StockMovement>>>{let q=supabase.from('stock_movements').select('*',{count:'exact'}).eq('company_id',cid).eq('stock_item_id',sid);const p=o?.page||1;const s=o?.pageSize||100;const{data,error,count}=await q.order('movement_date',{ascending:false}).range((p-1)*s,p*s-1);if(error)return he(error);return ok({data:data||[],count:count||0,error:null});}
export async function getVoucherSummary(cid:string,vt:string,fd?:string,td?:string):Promise<ApiResult<{totalAmount:number;totalCount:number;totalGst:number}>>{let q=supabase.from('vouchers').select('id,total_amount').eq('company_id',cid).eq('voucher_type',vt);if(fd)q=q.gte('voucher_date',fd);if(td)q=q.lte('voucher_date',td);const{data:vs,error}=await q;if(error)return he(error);const ta=(vs||[]).reduce((s,v)=>s+(v.total_amount||0),0);const tc=(vs||[]).length;let tg=0;if((vs||[]).length>0){const ids=vs!.map(v=>v.id);const{data:tx}=await supabase.from('voucher_taxes').select('amount').in('voucher_id',ids).in('tax_type',['CGST','SGST','IGST']);tg=(tx||[]).reduce((s,t)=>s+(t.amount||0),0);}return ok({totalAmount:ta,totalCount:tc,totalGst:tg});}
