// AKHILA AGENCIES ERP — SHARED TYPES

export interface Company { id: string; name: string; tally_name: string; short_code: string | null; address: string | null; gstin: string | null; phone: string | null; email: string | null; financial_year_start: string; is_active: boolean; created_at: string; updated_at: string; }
export interface Profile { id: string; display_name: string | null; email: string; is_admin: boolean; is_active: boolean; created_at: string; updated_at: string; }
export interface UserCompanyAccess { id: string; user_id: string; company_id: string; role: 'admin' | 'viewer'; created_at: string; }
export type LedgerClassification = 'customer' | 'supplier' | 'bank' | 'cash' | 'general';
export type BalanceType = 'Dr' | 'Cr';
export interface Ledger { id: string; company_id: string; tally_guid: string | null; master_id: string | null; name: string; parent_group: string | null; parent_group_id: string | null; opening_balance: number; closing_balance: number; balance_type: BalanceType | null; classification: LedgerClassification; is_customer: boolean; is_supplier: boolean; is_bank: boolean; is_cash: boolean; address: string | null; gstin: string | null; state_name: string | null; pin_code: string | null; contact_person: string | null; phone: string | null; email: string | null; pan: string | null; aadhar: string | null; opening_balance_date: string | null; created_at: string; updated_at: string; }
export interface LedgerGroup { id: string; company_id: string; tally_guid: string | null; name: string; parent_name: string | null; group_type: string | null; created_at: string; updated_at: string; }
export interface StockUnit { id: string; company_id: string; name: string; formal_name: string | null; }
export interface StockItem { id: string; company_id: string; tally_guid: string | null; master_id: string | null; name: string; parent_group: string | null; unit_name: string | null; unit_id: string | null; opening_balance: number; closing_balance: number; rate: number | null; gst_applicable: boolean; gst_rate: number | null; hsn_code: string | null; created_at: string; updated_at: string; }
export interface ManualStockBaseline { id: string; company_id: string; stock_item_id: string; quantity: number; unit: string | null; effective_date: string; reason: string | null; created_by: string | null; created_at: string; updated_at: string; }
export type VoucherType = 'Sales' | 'Purchase' | 'Receipt' | 'Payment' | 'Journal' | 'Contra' | 'Debit-Note' | 'Credit-Note' | string;
export interface Voucher { id: string; company_id: string; tally_guid: string | null; voucher_id_tally: string | null; alter_id: string | null; voucher_type: VoucherType; voucher_number: string | null; voucher_date: string; reference_number: string | null; party_ledger_id: string | null; party_name: string | null; narration: string | null; total_amount: number; total_debit: number; total_credit: number; is_cancelled: boolean; cancelled_date: string | null; synced_at: string; created_at: string; updated_at: string; items?: VoucherItem[]; ledger_entries?: VoucherLedgerEntry[]; taxes?: VoucherTax[]; }
export interface VoucherItem { id: string; voucher_id: string; company_id: string; stock_item_id: string | null; item_name: string; quantity: number; unit: string | null; rate: number; discount_percent: number; discount_amount: number; taxable_amount: number; amount: number; gst_rate: number | null; gst_amount: number; created_at: string; }
export interface VoucherLedgerEntry { id: string; voucher_id: string; company_id: string; ledger_id: string | null; ledger_name: string; is_deemed_positive: boolean; debit: number; credit: number; amount: number; entry_type: string | null; created_at: string; }
export interface VoucherTax { id: string; voucher_id: string; company_id: string; tax_type: string | null; ledger_name: string | null; ledger_id: string | null; amount: number; rate: number | null; created_at: string; }
export interface StockMovement { id: string; company_id: string; stock_item_id: string; voucher_id: string | null; movement_date: string; movement_type: 'purchase' | 'sale' | 'return-in' | 'return-out' | 'opening' | 'adjustment'; quantity_in: number; quantity_out: number; rate: number | null; amount: number | null; voucher_number: string | null; reference: string | null; created_at: string; }
export interface SyncState { id: string; company_id: string; initial_sync_completed: boolean; initial_sync_started_at: string | null; initial_sync_completed_at: string | null; last_successful_sync_at: string | null; last_successful_voucher_date: string | null; last_successful_voucher_boundary: string | null; current_sync_started_at: string | null; current_sync_status: 'idle' | 'running' | 'success' | 'failed' | 'partial'; current_sync_error: string | null; current_sync_progress: Record<string,unknown> | null; created_at: string; updated_at: string; }
export interface SyncRun { id: string; company_id: string; mode: 'initial' | 'incremental' | 'rebuild' | 'manual'; status: 'running' | 'success' | 'failed' | 'partial'; started_at: string; completed_at: string | null; date_range_start: string | null; date_range_end: string | null; voucher_count: number; ledger_count: number; stock_count: number; customer_count: number; supplier_count: number; bank_count: number; cash_count: number; error_message: string | null; error_detail: Record<string,unknown> | null; metadata: Record<string,unknown> | null; created_at: string; }
export interface ManualBankBalance { id: string; company_id: string; bank_ledger_id: string; balance: number; effective_date: string; reason: string | null; created_by: string | null; created_at: string; updated_at: string; }
export interface CompanySettings { id: string; company_id: string; primary_bank_ledger_id: string | null; sync_batch_months: number; sync_auto_enabled: boolean; sync_interval_min: number; tally_host: string; tally_port: number; default_currency_symbol: string; date_format: string; created_at: string; updated_at: string; }
export interface BankAccount { id: string; company_id: string; ledger_id: string; account_number: string | null; ifsc_code: string | null; branch_name: string | null; created_at: string; }
export interface CashAccount { id: string; company_id: string; ledger_id: string; created_at: string; }
export interface AuditLog { id: string; company_id: string | null; user_id: string | null; action: string; entity_type: string | null; entity_id: string | null; details: Record<string,unknown> | null; ip_address: string | null; created_at: string; }
export interface PaginationState { page: number; pageSize: number; totalCount: number; }
export interface PaginatedResponse<T> { data: T[]; count: number; error: string | null; }
export interface ApiResult<T> { data: T | null; error: string | null; }
export interface DateRangeFilter { fromDate: string; toDate: string; }
export interface DashboardData { topDebtors: Ledger[]; topCreditors: Ledger[]; recentVouchers: Voucher[]; }
