-- AKHILA AGENCIES ERP — INITIAL DATABASE SCHEMA
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE public.companies(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),name TEXT NOT NULL,tally_name TEXT NOT NULL,short_code TEXT,address TEXT,gstin TEXT,phone TEXT,email TEXT,financial_year_start TEXT DEFAULT '04-01',is_active BOOLEAN DEFAULT true,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.profiles(id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,display_name TEXT,email TEXT NOT NULL,is_admin BOOLEAN DEFAULT false,is_active BOOLEAN DEFAULT true,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.user_company_access(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,role TEXT DEFAULT 'viewer' CHECK(role IN('admin','viewer')),created_at TIMESTAMPTZ DEFAULT now(),UNIQUE(user_id,company_id));
CREATE TABLE public.ledger_groups(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,tally_guid TEXT,name TEXT NOT NULL,parent_name TEXT,group_type TEXT,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(company_id,tally_guid),UNIQUE(company_id,name));
CREATE TABLE public.ledgers(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,tally_guid TEXT,master_id TEXT,name TEXT NOT NULL,parent_group TEXT,parent_group_id TEXT,opening_balance NUMERIC(18,2) DEFAULT 0,closing_balance NUMERIC(18,2) DEFAULT 0,balance_type TEXT CHECK(balance_type IN('Dr','Cr')),classification TEXT CHECK(classification IN('customer','supplier','bank','cash','general')),is_customer BOOLEAN DEFAULT false,is_supplier BOOLEAN DEFAULT false,is_bank BOOLEAN DEFAULT false,is_cash BOOLEAN DEFAULT false,address TEXT,gstin TEXT,state_name TEXT,pin_code TEXT,contact_person TEXT,phone TEXT,email TEXT,pan TEXT,aadhar TEXT,opening_balance_date DATE,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(company_id,tally_guid),UNIQUE(company_id,master_id));
CREATE TABLE public.stock_units(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,name TEXT NOT NULL,formal_name TEXT,created_at TIMESTAMPTZ DEFAULT now(),UNIQUE(company_id,name));
CREATE TABLE public.stock_items(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,tally_guid TEXT,master_id TEXT,name TEXT NOT NULL,parent_group TEXT,unit_name TEXT,unit_id UUID REFERENCES public.stock_units(id),opening_balance NUMERIC(18,4) DEFAULT 0,closing_balance NUMERIC(18,4) DEFAULT 0,rate NUMERIC(18,2),gst_applicable BOOLEAN DEFAULT false,gst_rate NUMERIC(5,2),hsn_code TEXT,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(company_id,tally_guid),UNIQUE(company_id,master_id));
CREATE TABLE public.vouchers(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,tally_guid TEXT,voucher_id_tally TEXT,alter_id TEXT,voucher_type TEXT NOT NULL,voucher_number TEXT,voucher_date DATE NOT NULL,reference_number TEXT,party_ledger_id UUID REFERENCES public.ledgers(id),party_name TEXT,narration TEXT,total_amount NUMERIC(18,2) DEFAULT 0,total_debit NUMERIC(18,2) DEFAULT 0,total_credit NUMERIC(18,2) DEFAULT 0,is_cancelled BOOLEAN DEFAULT false,cancelled_date DATE,synced_at TIMESTAMPTZ DEFAULT now(),created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(company_id,tally_guid),UNIQUE(company_id,voucher_number,voucher_type,voucher_date));
CREATE TABLE public.voucher_items(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),voucher_id UUID NOT NULL REFERENCES public.vouchers(id) ON DELETE CASCADE,company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,stock_item_id UUID REFERENCES public.stock_items(id),item_name TEXT NOT NULL,quantity NUMERIC(18,4) DEFAULT 0,unit TEXT,rate NUMERIC(18,2) DEFAULT 0,discount_percent NUMERIC(5,2) DEFAULT 0,discount_amount NUMERIC(18,2) DEFAULT 0,taxable_amount NUMERIC(18,2) DEFAULT 0,amount NUMERIC(18,2) DEFAULT 0,gst_rate NUMERIC(5,2),gst_amount NUMERIC(18,2) DEFAULT 0,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.voucher_ledger_entries(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),voucher_id UUID NOT NULL REFERENCES public.vouchers(id) ON DELETE CASCADE,company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,ledger_id UUID REFERENCES public.ledgers(id),ledger_name TEXT NOT NULL,is_deemed_positive BOOLEAN DEFAULT true,debit NUMERIC(18,2) DEFAULT 0,credit NUMERIC(18,2) DEFAULT 0,amount NUMERIC(18,2) DEFAULT 0,entry_type TEXT,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.voucher_taxes(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),voucher_id UUID NOT NULL REFERENCES public.vouchers(id) ON DELETE CASCADE,company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,tax_type TEXT,ledger_name TEXT,ledger_id UUID REFERENCES public.ledgers(id),amount NUMERIC(18,2) DEFAULT 0,rate NUMERIC(5,2),created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.stock_movements(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,stock_item_id UUID NOT NULL REFERENCES public.stock_items(id),voucher_id UUID REFERENCES public.vouchers(id) ON DELETE SET NULL,movement_date DATE NOT NULL,movement_type TEXT CHECK(movement_type IN('purchase','sale','return-in','return-out','opening','adjustment')),quantity_in NUMERIC(18,4) DEFAULT 0,quantity_out NUMERIC(18,4) DEFAULT 0,rate NUMERIC(18,2),amount NUMERIC(18,2),voucher_number TEXT,reference TEXT,created_at TIMESTAMPTZ DEFAULT now(),UNIQUE(company_id,stock_item_id,voucher_id,movement_type,movement_date));
CREATE TABLE public.sync_state(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE UNIQUE,initial_sync_completed BOOLEAN DEFAULT false,initial_sync_started_at TIMESTAMPTZ,initial_sync_completed_at TIMESTAMPTZ,last_successful_sync_at TIMESTAMPTZ,last_successful_voucher_date DATE,last_successful_voucher_boundary TEXT,current_sync_started_at TIMESTAMPTZ,current_sync_status TEXT DEFAULT 'idle' CHECK(current_sync_status IN('idle','running','success','failed','partial')),current_sync_error TEXT,current_sync_progress JSONB,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.sync_runs(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,mode TEXT NOT NULL CHECK(mode IN('initial','incremental','rebuild','manual')),status TEXT NOT NULL CHECK(status IN('running','success','failed','partial')),started_at TIMESTAMPTZ DEFAULT now(),completed_at TIMESTAMPTZ,date_range_start DATE,date_range_end DATE,voucher_count INTEGER DEFAULT 0,ledger_count INTEGER DEFAULT 0,stock_count INTEGER DEFAULT 0,customer_count INTEGER DEFAULT 0,supplier_count INTEGER DEFAULT 0,bank_count INTEGER DEFAULT 0,cash_count INTEGER DEFAULT 0,error_message TEXT,error_detail JSONB,metadata JSONB,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.manual_stock_baselines(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,stock_item_id UUID NOT NULL REFERENCES public.stock_items(id),quantity NUMERIC(18,4) NOT NULL,unit TEXT,effective_date DATE NOT NULL DEFAULT CURRENT_DATE,reason TEXT,created_by UUID REFERENCES public.profiles(id),created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(company_id,stock_item_id));
CREATE TABLE public.manual_bank_balances(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,bank_ledger_id UUID NOT NULL REFERENCES public.ledgers(id),balance NUMERIC(18,2) NOT NULL,effective_date DATE NOT NULL DEFAULT CURRENT_DATE,reason TEXT,created_by UUID REFERENCES public.profiles(id),created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(company_id,bank_ledger_id));
CREATE TABLE public.company_settings(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE UNIQUE,primary_bank_ledger_id UUID REFERENCES public.ledgers(id),sync_batch_months INTEGER DEFAULT 1,sync_auto_enabled BOOLEAN DEFAULT false,sync_interval_min INTEGER DEFAULT 30,tally_host TEXT DEFAULT 'localhost',tally_port INTEGER DEFAULT 9000,default_currency_symbol TEXT DEFAULT '₹',date_format TEXT DEFAULT 'DD/MM/YYYY',created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.audit_logs(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID REFERENCES public.companies(id) ON DELETE SET NULL,user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,action TEXT NOT NULL,entity_type TEXT,entity_id UUID,details JSONB,ip_address TEXT,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.cash_accounts(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,ledger_id UUID NOT NULL REFERENCES public.ledgers(id) ON DELETE CASCADE UNIQUE,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.bank_accounts(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,ledger_id UUID NOT NULL REFERENCES public.ledgers(id) ON DELETE CASCADE UNIQUE,account_number TEXT,ifsc_code TEXT,branch_name TEXT,created_at TIMESTAMPTZ DEFAULT now());

-- Indexes
CREATE INDEX idx_ledgers_company ON public.ledgers(company_id);
CREATE INDEX idx_ledgers_tally_guid ON public.ledgers(tally_guid);
CREATE INDEX idx_ledgers_class ON public.ledgers(company_id,classification);
CREATE INDEX idx_vouchers_company ON public.vouchers(company_id);
CREATE INDEX idx_vouchers_date ON public.vouchers(company_id,voucher_date DESC);
CREATE INDEX idx_vouchers_type ON public.vouchers(company_id,voucher_type);
CREATE INDEX idx_vle_voucher ON public.voucher_ledger_entries(voucher_id);
CREATE INDEX idx_vle_ledger ON public.voucher_ledger_entries(ledger_id);
CREATE INDEX idx_stock_items_company ON public.stock_items(company_id);
CREATE INDEX idx_stock_movements_item ON public.stock_movements(stock_item_id);
CREATE INDEX idx_sync_runs_company ON public.sync_runs(company_id,started_at DESC);

-- RLS: Enable on all tables
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ledgers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vouchers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voucher_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voucher_ledger_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voucher_taxes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manual_stock_baselines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manual_bank_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Auto-create profile trigger
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS TRIGGER AS $$ BEGIN INSERT INTO public.profiles(id,display_name,email) VALUES(NEW.id,COALESCE(NEW.raw_user_meta_data->>'display_name',NEW.email),NEW.email);RETURN NEW;END;$$ LANGUAGE plpgsql SECURITY DEFINER;
CREATE TRIGGER trg_handle_new_user AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Policies: Users read own company data
CREATE POLICY ledgers_r ON public.ledgers FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY stock_r ON public.stock_items FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY vouchers_r ON public.vouchers FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY vi_r ON public.voucher_items FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY vle_r ON public.voucher_ledger_entries FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY vt_r ON public.voucher_taxes FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY sm_r ON public.stock_movements FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY ss_r ON public.sync_state FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY sr_r ON public.sync_runs FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY msb_r ON public.manual_stock_baselines FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY mbb_r ON public.manual_bank_balances FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY cs_r ON public.company_settings FOR SELECT TO authenticated USING(company_id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
CREATE POLICY companies_r ON public.companies FOR SELECT TO authenticated USING(id IN(SELECT company_id FROM public.user_company_access WHERE user_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_admin=true));
